[build]
  base = "frontend"          # Path to your project root (where package.json lives)
  publish = "dist"  # Built output directory
  command = "npm install --legacy-peer-deps && npm run build" # Build command

[build.environment]
  NODE_VERSION = "20"        # Match your local Node.js version
  NPM_FLAGS = "--legacy-peer-deps" # Force legacy deps handling

# Optional (for framework detection)
[dev]
  framework = "vite"