import React from 'react';
import { createPortal } from 'react-dom';

const TermsOfService = () => {
    return createPortal(
        <div className="fixed inset-0 z-50 bg-white overflow-y-auto p-4 md:p-8">
            <div className="max-w-4xl mx-auto bg-white text-gray-800">
                <h1 className="text-3xl md:text-4xl font-bold mb-4 text-gray-900">Terms of Service</h1>
                <p className="italic text-sm mb-8 text-gray-600">Last Updated: 3/7/2025</p>

                <div className="space-y-8">
                    <section>
                        <h2 className="text-xl font-bold mt-6 mb-4 text-gray-900">1. Overview of Our Service</h2>
                        <p className="text-gray-700 leading-relaxed">
                            These Terms of Service ("Terms") govern your access to
                            and use of our ecommerce platform and associated services, including both the client-facing shopping site and the admin
                            management area. By accessing or using our Service, you agree to be bound by these Terms, as well as by any additional
                            terms referenced herein or provided to you in connection with specific features.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mt-6 mb-4 text-gray-900">2. Eligibility and Account Setup</h2>
                        <div className="space-y-4">
                            <div>
                                <span className="font-semibold text-gray-900">Eligibility:</span>
                                <p className="mt-2 text-gray-700 leading-relaxed">
                                    You must be at least 18 years old and possess a valid Facebook Business Account, and an associated Instagram
                                    Business or Creator Account, in order to use the Service.
                                </p>
                            </div>
                            <div>
                                <span className="font-semibold text-gray-900">Account Creation:</span>
                                <p className="mt-2 text-gray-700 leading-relaxed">
                                    When the Service is first hosted, the first user to log in with their Facebook account will be designated as
                                    the website owner. This account is solely responsible for managing administrative access. No other Facebook
                                    account may log into the admin area unless invited via a passkey generated by the website owner.
                                </p>
                            </div>
                        </div>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold mt-6 mb-4 text-gray-900">3. Passkey System and Access Control</h2>
                        <ul className="list-disc pl-6 space-y-4">
                            <li className="text-gray-700">
                                <span className="font-semibold">Passkey Generation:</span>
                                <p className="mt-1 leading-relaxed">
                                    The website owner may generate unique passkey strings (hashes) with predefined privileges (e.g., Admin, Editor,
                                    Viewer, Billing) using the Passkey Management functionality in the admin interface. These passkeys serve as a
                                    passwordless means to grant secondary users access to the admin area.
                                </p>
                            </li>
                            <li className="text-gray-700">
                                <span className="font-semibold">Access Rights:</span>
                                <p className="mt-1 leading-relaxed">
                                    Passkeys are tied to specific privileges that determine what parts of the admin page a secondary user may access.
                                    The website owner is responsible for assigning, monitoring, and revoking these passkeys.
                                </p>
                            </li>
                            <li className="text-gray-700">
                                <span className="font-semibold">Usage and Logs:</span>
                                <p className="mt-1 leading-relaxed">
                                    All login activities and actions performed by secondary users via passkeys are logged. The website owner retains
                                    full visibility of these logs for security and audit purposes.
                                </p>
                            </li>
                        </ul>
                    </section>

                    {/* Repeat similar structure for other sections */}

                    <section>
                        <h2 className="text-xl font-bold mt-6 mb-4 text-gray-900">10. Contact Us</h2>
                        <p className="text-gray-700 leading-relaxed">
                            If you have any questions about these Terms, please contact us at:
                            <br />
                            <a
                                href="mailto:onuertey1997@gmail.com?subject=Inquiry%20from%20[Your%20Website%20Name]&body=Hello,%0D%0A%0D%0APlease include your website domain name and any other relevant information in your message.%0D%0A%0D%0AThank you."
                                className="text-blue-600 hover:text-blue-800 underline transition-colors"
                            >
                                onuertey1997@gmail.com
                            </a>

                        </p>
                    </section>

                    <div className="mt-8 p-4 bg-gray-50 rounded-lg border border-gray-200">
                        <p className="font-semibold text-center text-gray-700">
                            By using our Service, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                        </p>
                    </div>
                </div>
            </div>
        </div>,
        document.body
    );
};

export default TermsOfService;